import {Grid, Text} from '@sanity/ui'
import {ActionDispatch} from 'react'

import {Secrets, UploadConfig} from '../../util/types'
import {UploadConfigurationStateAction} from '../UploadConfiguration'
import PlaybackPolicyOption from './PlaybackPolicyOption'
import PlaybackPolicyWarning from './PlaybackPolicyWarning'

export default function PlaybackPolicy({
  id,
  config,
  secrets,
  dispatch,
}: {
  id: string
  config: UploadConfig
  secrets: Secrets
  dispatch: ActionDispatch<[action: UploadConfigurationStateAction]>
}) {
  const noPolicySelected = !(config.public_policy || config.signed_policy || config.drm_policy)
  const drmPolicyDisabled = !secrets.drmConfigId
  return (
    <Grid gap={3}>
      <Text weight="bold">Advanced Playback Policies</Text>
      <PlaybackPolicyOption
        id={`${id}--public`}
        checked={config.public_policy}
        optionName="Public"
        description="Playback IDs are accessible by constructing an HLS URL like https://stream.mux.com/{PLAYBACK_ID}"
        dispatch={dispatch}
        action="public_policy"
      />
      {secrets.enableSignedUrls && (
        <PlaybackPolicyOption
          id={`${id}--signed`}
          checked={config.signed_policy}
          optionName="Signed"
          description="Playback IDs should be used with tokens https://stream.mux.com/{PLAYBACK_ID}?token={TOKEN}. 
                // See Secure video playback for details about creating tokens."
          dispatch={dispatch}
          action="signed_policy"
        />
      )}
      {drmPolicyDisabled ? (
        <PlaybackPolicyOption
          id={`${id}--drm`}
          checked={false}
          optionName="DRM - Disabled"
          description="To enable DRM add your DRM Configuration Id to your plugin configuration. Contact us to get started using DRM."
          dispatch={dispatch}
          disabled
        />
      ) : (
        <PlaybackPolicyOption
          id={`${id}--drm`}
          checked={config.drm_policy}
          optionName="DRM"
          description="DRM Configuration should be used with tokens https://license.mux.com/license/{DRM_SYSTEM}/{PLAYBACK_ID}?token={TOKEN}.\n
                 Where DRM_SYSTEM is one of ('widevine' | 'playready' | 'fairplay')\n
                 For FairPlay also set certificate https://license.mux.com/certificate/fairplay/{PLAYBACK_ID}?token={TOKEN}\n
                 See Secure video playback for details about creating tokens."
          dispatch={dispatch}
          action="drm_policy"
        />
      )}
      {noPolicySelected && <PlaybackPolicyWarning />}
    </Grid>
  )
}

/* const DrmConfig = ({
  drmEnabled,
  dispatch,
  disabled,
}: {
  drmEnabled: boolean
  disabled: boolean
  dispatch: Dispatch<{action: 'drm_enabled'; value: UploadConfig['drm_enabled']}>
}) => {
  const description = disabled
    ? ''
    : ''
  const checkboxLabel = disabled ? 'DRM Enabled' : 'DRM Enabled'
  return (
    <FormField
      title="Protect Content with DRM (Digital Rights Management)"
      description={description}
    >
      <Stack space={2}>
        <Flex align="center">
          <Checkbox
            id="include-autogenerated-track"
            style={{display: 'block'}}
            checked={drmEnabled}
            disabled={disabled}
            onChange={() => {
              dispatch({action: 'drm_enabled', value: !drmEnabled})
            }}
          />
          <Box flex={1} paddingLeft={3}>
            <Text>
              <label htmlFor="checkbox">{checkboxLabel}</label>
            </Text>
          </Box>
        </Flex>
      </Stack>
    </FormField>
  )
} */
