name: Publish

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to NPM
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          package-manager-cache: false 
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
